# version: '3.8'
services:
  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - '3001:3000'
    depends_on:
      - kafka
      - mongodb-auth
    environment:
      - mongodb+srv://radhika:microservices@microservices.lpvgrrr.mongodb.net/auth-db

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - '3002:3000' # or the appropriate port
    depends_on:
      - kafka
      - mongodb-user
    environment:
      - mongodb+srv://radhika:microservices@microservices.lpvgrrr.mongodb.net/user-db

  notification-service:
    build:
      context: ./notification-service
      dockerfile: Dockerfile
    depends_on:
      - kafka
    restart: unless-stopped

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    ports:
      - '9092:9092'
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/custom.conf
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - user-service
      # - product-service
